# ***********************************************************************
#
# $HeadURL$
# $LastChangedDate$
# $LastChangedBy$
# $LastChangedRevision$
#
# ***********************************************************************

include ../config.mk
include ../rules.mk

SUBDIRS= \
fltype_-2 \
fltype_3 \

###########################################################################

all:
	@echo " " ; echo " Nothing to be done for all" ; echo " "

test: $(SUBDIRS:%=%.test)

clean: $(SUBDIRS:%=%.clean)
