# ***********************************************************************
#
# $HeadURL: https://www.mech.kth.se/svn/simson/trunk/pext1/Makefile.config $
# $LastChangedDate: 2010-09-03 14:57:59 +0200 (Fri, 03 Sep 2010) $
# $LastChangedBy: mattias@MECH.KTH.SE $
# $LastChangedRevision: 1504 $
#
# ***********************************************************************

# Makefile for Simson pext1

# Gobal configuration file
include ../config.mk

# Gobal Makefile rules
include ../rules.mk

# Define fortran files in use
main    = pext1
plot    = plot1.o

# Files independent of par.f
idep    = $(main).o $(plot)

# Big/little endian (big endian is default)
ifeq "$(lendian)" "yes"
	ENDIAN = $(LEND_FLAG)
else
	ENDIAN = $(BEND_FLAG)
endif


all: $(main)$(EXESUFFIX)

$(main)$(EXESUFFIX): $(idep) Makefile.config
	@echo " " ; echo " Linking object files into executable image '$(main)$(EXESUFFIX)'"
	@echo " "
	$(F90) $(LDFLAGS) $(ENDIAN) -o $@ $(idep)
	@echo " " ; echo " Done!" ; echo " "

clean:
	@echo " " ; echo " Cleaning up all object files and '$(main)$(EXESUFFIX)'"
	@-rm -f *.o $(main)$(EXESUFFIX) ; echo " "

dist:

install: $(main)$(EXESUFFIX)
	@echo " " ; echo " Installing $(main)$(EXESUFFIX) in $(prefix)/bin/$(main)$(EXESUFFIX)" ;\
	$(INSTALL) $(main)$(EXESUFFIX) $(prefix)/bin/ ; echo " "
