############################################################################
#                   Makefile for Nolot
#  System specific changes should not be made in this file.
############################################################################
#
# $HeadURL: https://ikaros.foi.se/svn/nolot/trunk/examples/Makefile $
# $LastChangedDate: 2007-08-15 08:47:50 +0200 (Wed, 15 Aug 2007) $
# $LastChangedBy: crm $
# $LastChangedRevision: 223 $
#
include ../../config.mk
include ../../rules.mk

###########################################################################

all:
	@echo " " ; echo " Nothing to be done for all" ; echo " "

test:
	@./test.py

clean:
