# ***********************************************************************
#
# $HeadURL: https://www.mech.kth.se/svn/simson/trunk/cmp/Makefile.config $
# $LastChangedDate: 2010-09-03 14:59:12 +0200 (Fri, 03 Sep 2010) $
# $LastChangedBy: mattias@MECH.KTH.SE $
# $LastChangedRevision: 1505 $
#
# ***********************************************************************

# Makefile for Simson cmp

# Gobal configuration file
include ../config.mk

# Gobal Makefile rules
include ../rules.mk

# Define fortran files in use
main    = cmp
read    = rdisca.o
write   = wdisca.o
get     = getxy.o getxz.o
put     = putxy.o putxz.o
amp     = wcamp.o namp.o boxamp.o
ext     = wcext.o boxext.o plnmax.o plnmin.o fft2db.o fft2df.o
comp    = add.o comxz.o dcheb.o power.o
symm    = symm_z.o

# Dependent files on par.f
dep     = $(main).o $(read) $(write) $(get) $(put) $(comp) $(symm) $(amp) $(ext)

# Independent files
idep    = $(FFTPACK).o

obj     = $(dep) $(idep)

# Big/little endian (big endian is default)
ifeq "$(lendian)" "yes"
	ENDIAN = $(LEND_FLAG)
else
	ENDIAN = $(BEND_FLAG)
endif


all: $(main)$(EXESUFFIX)

$(main)$(EXESUFFIX): $(obj) Makefile.config
	@echo " " ; echo " Linking object files into executable image '$(main)$(EXESUFFIX)'"
	@echo " "
	$(F90) $(LDFLAGS) $(ENDIAN) -o $@ $(obj)
	@echo " " ; echo " Done!" ; echo " "

$(dep):	par.f

clean:
	@echo " " ; echo " Cleaning up all object files and '$(main)$(EXESUFFIX)'"
	@-rm -f *.o $(main)$(EXESUFFIX) ; echo " "

dist:
	@echo " " ; echo " Copying global $(PARAM) to $(main) directory as par.f" ; echo " "
	@cp ../$(PARAM) par.f

install: $(main)$(EXESUFFIX)
	@echo " " ; echo " Installing $(main)$(EXESUFFIX) in $(prefix)/bin/$(main)$(EXESUFFIX)" ;\
	$(INSTALL) $(main)$(EXESUFFIX) $(prefix)/bin/ ; echo " "
