# ***********************************************************************
#
# $HeadURL: https://www.mech.kth.se/svn/simson/trunk/fou/Makefile.config $
# $LastChangedDate: 2010-09-03 14:59:12 +0200 (Fri, 03 Sep 2010) $
# $LastChangedBy: mattias@MECH.KTH.SE $
# $LastChangedRevision: 1505 $
#
# ***********************************************************************

# Makefile for Simson fou

# Gobal configuration file
include ../config.mk

# Gobal Makefile rules
include ../rules.mk

# Define fortran files in use
main    = fou
read    = rdiscr.o
get     = getxzp.o
put     = putxyp.o
pg      = pgmr.o wpgmr.o
plot    = contfou.o splint.o curvefit.o svdcmp.o svbksb.o newton.o \
          plot1.o savelist.o foustr.o

# Files dependent on par.f
dep     = $(main).o $(read) $(get) $(put) foubranch.o spline.o

# Files independent of par.f
idep    = $(plot) $(FFTPACK).o $(pg)

# Big/little endian (big endian is default)
ifeq "$(lendian)" "yes"
	ENDIAN = $(LEND_FLAG)
else
	ENDIAN = $(BEND_FLAG)
endif


all: $(main)$(EXESUFFIX)

$(main)$(EXESUFFIX): $(dep) $(idep) Makefile.config
	@echo " " ; echo " Linking object files into executable image '$(main)$(EXESUFFIX)'"
	@echo " "
	$(F90) $(LDFLAGS) $(ENDIAN) -o $@ $(dep) $(idep)
	@echo " " ; echo " Done!" ; echo " "

$(dep):	par.f

clean:
	@echo " " ; echo " Cleaning up all object files and '$(main)$(EXESUFFIX)'"
	@-rm -f *.o $(main)$(EXESUFFIX) ; echo " "

dist:
	@echo " " ; echo " Copying global $(PARAM) to $(main) directory as par.f" ; echo " "
	@cp ../$(PARAM) par.f

install: $(main)$(EXESUFFIX)
	@echo " " ; echo " Installing $(main)$(EXESUFFIX) in $(prefix)/bin/$(main)$(EXESUFFIX)" ;\
	$(INSTALL) $(main)$(EXESUFFIX) $(prefix)/bin/ ; echo " "
