# ***********************************************************************
#
# $HeadURL: https://www.mech.kth.se/svn/simson/trunk/paraview/paraviewscripts/Makefile.config $
# $LastChangedDate: 2010-11-09 22:03:21 +0100 (Tue, 09 Nov 2010) $
# $LastChangedBy: mattias@MECH.KTH.SE $
# $LastChangedRevision: 1615 $
#
# ***********************************************************************

# Makefile for Simson ParaView scripts

# Gobal configuration file
include ../../config.mk

# Gobal Makefile rules
include ../../rules.mk

main  = __init__.py \
      	setup_movie.py \
	circle.py

all: $(main)


clean:
	@echo " " ; echo " Cleaning up all compiled python files"
	@-rm -f *.pyc  ; echo " "

install:
	@echo " " ; echo " Installing $(main) in $(prefix)/bin/paraviewscripts/" ;\
	$(INSTALL) $(main) $(prefix)/bin/paraviewscripts/ ; echo " "
