# ***********************************************************************
#
# $HeadURL: https://www.mech.kth.se/svn/simson/trunk/paraview/Makefile.config $
# $LastChangedDate: 2010-11-03 22:35:53 +0100 (Wed, 03 Nov 2010) $
# $LastChangedBy: mattias@MECH.KTH.SE $
# $LastChangedRevision: 1608 $
#
# ***********************************************************************

# Makefile for Simson ParaView scripts

# Gobal configuration file
include ../config.mk

# Gobal Makefile rules
include ../rules.mk

main  = driver.py

SUBDIRS= \
paraviewscripts \


all: $(main) $(SUBDIRS:%=%.all)


clean:
	@echo " " ; echo " Cleaning up all compiled python files"
	@-rm -f *.pyc  ; echo " "

install:
	@echo " " ; echo " Installing $(main) in $(prefix)/bin/" ;\
	$(INSTALL) $(main) $(prefix)/bin/ ; echo " "
